### ISSUE TITLE
LICENCE is missing

### ISSUE THREAD

**Issue by dimkir** [lightster/named-sprintf#51]
Would be great to have MIT or APACHE licence for the project

**Comment by lightster** [comment]
Hi there @dimkir!

The project is actually already under the MIT license :smile: See [LICENSE](https://github.com/lightster/named-sprintf/blob/master/LICENSE) at the root of the repo.

I do see that I do not have the license listed in Composer, but I will work to get that taken care of.

Thanks for checking out named-sprintf. Please let me know if you need any help or have any suggestions.
