### ISSUE TITLE
preg_match_all(): Unknown modifier '

### ISSUE THREAD

**Issue by phuongdm1987** [lightster/named-sprintf#61]
in vendor/lightster/named-sprintf/src/Processor.php

change:

        $pattern = '
            @
                (
                    (?:^|[^%])
                    (?:%%)*%
                ) # 1: the percent sign(s)
                \( # literal open paren
                    ([a-zA-Z_][a-zA-Z0-9_\-,:]*?) # 2: the name of the param
                \) # literal close paren
                (
                    (?:
                        # standard sprintf format. reference http://php.net/sprintf
                        [+]?                # an optional +/- sign specifier
                        (?:[ 0]|\'.)?       # an optional space/zero padding specifier or
                                            # alternative padding character prefixed by a single quote
                        [\-]?               # an optional alignment specifier
                                            # ("-" for left-justified; right-justified otherwise)
                        \d*                 # an optional width specifier
                        (?:\.(?:.?\d+)?)?   # an optional precision specifier
                                            # (a dot "." followed by an optional number, with an optional
                                            # padding character in between the dot and the number)
                        [bcdeEfFgGosuxX]    # the type specifier
                    )?
                ) # 3: the standard sprintf format
            @mx
        ';

to

        $pattern = '@
                (
                    (?:^|[^%])
                    (?:%%)*%
                ) # 1: the percent sign(s)
                \( # literal open paren
                    ([a-zA-Z_][a-zA-Z0-9_\-,:]*?) # 2: the name of the param
                \) # literal close paren
                (
                    (?:
                        # standard sprintf format. reference http://php.net/sprintf
                        [+]?                # an optional +/- sign specifier
                        (?:[ 0]|\'.)?       # an optional space/zero padding specifier or
                                            # alternative padding character prefixed by a single quote
                        [\-]?               # an optional alignment specifier
                                            # ("-" for left-justified; right-justified otherwise)
                        \d*                 # an optional width specifier
                        (?:\.(?:.?\d+)?)?   # an optional precision specifier
                                            # (a dot "." followed by an optional number, with an optional
                                            # padding character in between the dot and the number)
                        [bcdeEfFgGosuxX]    # the type specifier
                    )?
                ) # 3: the standard sprintf format
            @mx';

remove '\n' at first and end of $pattern to fix it. thanks

**Comment by lightster** [comment]
Hi there @phuongdm1987,

Thanks for the report!

I am trying to reproduce the issue so I can add tests to prevent regressions. I have been unable to reproduce the error on PHP 7.0, 7.1, or 7.2. What version of PHP are you running?

Thanks,

Matt Light

**Comment by phuongdm1987** [comment]
Hi @lightster ,

some guys in team use window 10 and php 7.2
I test on http://sandbox.onlinephpfunctions.com/ with php 7.2 
and error return "preg_match_all(): Unknown modifier '"

please help, thanks!

**Comment by lightster** [comment]
Hi @phuongdm1987,

I just released v0.2.1, which changes the way I quote the regular expression. I was able to reproduce the error in the sandbox link you sent me, though I still was unable to reproduce in my Docker or Travis CI environments. Thanks for that link—otherwise I would have not been able to reproduce at all!

Please test and, if possible, have some of your team test the updated version.

Thanks so much,

@lightster
